---
- hosts: wordpress

  vars:
    compose_ver: 1.15.0
    db_ip: "{{ dp_ip }}"


  tasks:

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python-setuptools
        - python-pip

    - name: Docker-PY
      pip:
        name: "{{ item }}"
      with_items:
      - six==1.4
      - docker-py==1.1.0

    - name: install extra pkg for ubuntu 14.04
      apt:
       name: "{{ item }}"
       update_cache: yes
      with_items:
      - linux-image-extra-4.4.0-96-generic
      - linux-image-extra-virtual

    - name: Add Docker’s official GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

    - name: Set Stable repo
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

    - name: apt update
      apt: update_cache=yes

    - name: Install Docker
      apt:
       name: docker-ce

    - name: run wordpress
      shell: docker run -itd -e WORDPRESS_DB_HOST={{ db_ip }}:3306 -e WORDPRESS_DB_USER=root -e WORDPRESS_DB_PASSWORD=Password1234 -p 80:80 --name wordpress wordpress
